server:
  port: 8081
  error:
    include-message: never
    include-stacktrace: never
    include-binding-errors: never

spring:
  application:
    name: message-me
  jackson:
    default-property-inclusion: non_null
  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 6MB

management:
  endpoints:
    web:
      exposure:
        include: health
  endpoint:
    health:
      show-details: never
